# 어벤디2 2주차 실습 1

In [1]:
import cv2

img_color = cv2.imread("Desktop/images/cat on laptop.jpg", cv2.IMREAD_COLOR)

if img_color is None:
  print("not thing this file")
  exit(1)

In [2]:
cv2.namedWindow('Color')

cv2.imshow('Color', img_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 어벤디2 2주차 실습 2

In [3]:
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

cv2.imshow("Grayscale Image", img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
cv2.imwrite("Grayscale.jpg", img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 어벤디2 2주차 실습 3

In [6]:
import cv2 as cv

img_gray = cv.imread("Desktop/images/cat on laptop.jpg", cv.IMREAD_GRAYSCALE)

img_copy = img_gray

print(id(img_gray), id(img_copy))

2301633673232 2301633673232


In [7]:
cv.line(img_gray, (0, 0), (100, 100), 0, 10)

array([[  0,   0,   0, ...,  50,  43,  42],
       [  0,   0,   0, ...,  44,  39,  40],
       [  0,   0,   0, ...,  66,  65,  71],
       ...,
       [ 93,  96,  97, ..., 101, 106, 103],
       [ 87,  95,  93, ...,  95,  93,  91],
       [103, 108,  95, ...,  53,  60,  66]], dtype=uint8)

In [8]:
cv.imshow("Grayscale Image", img_gray)
cv.imshow("Copied Image", img_copy)

cv.waitKey(0)
cv.destroyAllWindows()

# 어벤디2 2주차실습 4

In [9]:
import cv2 as cv
import numpy as np

img_color = cv.imread("Desktop/images/apple.png", cv.IMREAD_COLOR)

height, width = img_color.shape[:2]

print(height, width)

267 400


In [10]:
img_gray = np.zeros((height, width), np.uint8)
print(img_gray)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
for y in range(0, height):
    for x in range(0, width):
        b = img_color.item(y, x, 0)
        g = img_color.item(y, x, 1)
        r = img_color.item(y, x, 2)

        gray = int(r*0.2126 + g*0.7152 + b*0.0722)

        img_gray.itemset((y, x), gray)

img_result = cv.cvtColor(img_gray, cv.COLOR_GRAY2BGR)

In [12]:
for y in range(150, 201):
    for x in range(200, 251):
        img_result.itemset((y, x, 0), 0)
        img_result.itemset((y, x, 1), 255)
        img_result.itemset((y, x, 2), 0)

cv.imshow("color Image", img_color)
cv.imshow("result Image", img_result)

cv.waitKey(0)
cv.destroyAllWindows()


# 어벤디2 2주차 실습 5

In [2]:
import cv2 as cv

cap = cv.VideoCapture(0)

if cap.isOpened() == False:
    print("not thing this file")
    exit(1)

In [4]:
while(True):
    ret, img_frame = cap.read()

    if ret == False:
        print("false")
        break

    cv.imshow('Color', img_frame)

    key = cv.waitKey(1)

    if key == ord('q'):
        break

cap.release()

cv.destroyAllWindows()

false


# 어벤디2 2주차 실습6

In [17]:
import cv2 as cv

cap = cv.VideoCapture(0)

if cap.isOpened() == False:
    print("not thing this file")
    exit(1)

ret, img_frame = cap.read()

if ret == False:
        print("false")
        exit(1)

h,w = img_frame.shape[:2]

In [18]:
codec = cv.VideoWriter_fourcc('M','J','P','G')

fps = 30.0

writer = cv.VideoWriter('output.avi', codec, fps, (w,h))

if writer.isOpened() == False:
    print("false")
    exit(1)

In [19]:
while(True):
    ret, img_frame = cap.read()

    if ret == False:
        print("false")
        break

    writer.write(img_frame)
    
    cv.imshow('Color', img_frame)

    key = cv.waitKey(1)

    if key == ord('q'):
        break

cap.release()

writer.release()

cv.destroyAllWindows()

In [20]:
cap = cv.VideoCapture('output.avi')

if cap.isOpened() == False:
    print("false")
    exit(1)

while(True):
    ret, img_frame = cap.read()

    if ret == False:
        print("false")
        break

    cv.imshow('Color', img_frame)

    key = cv.waitKey(25)

    if key == ord('q'):
        break

cap.release()

cv.destroyAllWindows()

false
